fix: fix `parent_conn` not initialize
pycasbin/postgresql-watcher pull request #11
Opened 2021-05-11 07:27 UTC by Zxilly

Signed-off-by: Zxilly <zhouxinyu1001@gmail.com>

2021-05-11 11:41 UTC, ffyuanda commented
nb

2021-05-11 15:16 UTC, hsluoyz commented
@techoner

2021-05-12 15:05 UTC, techoner requested changes

2021-05-12 15:05 UTC, techoner commented on postgresql_watcher/watcher.py
> +        channel_name: Optional[str] = POSTGRESQL_CHANNEL_NAME,
Incorrect indentation format , it also exists elsewhere

2021-05-19 16:01 UTC, hsluoyz commented
@techoner

2021-05-19 16:02 UTC, merged